### ISSUE TITLE
Enhance this project with CMU phonemes?

### ISSUE THREAD

**Issue by GeorgeS2019** [kaiidams/Voice100Godot#1]
@kaiidams  Would you consider integrating this [PR ](https://github.com/kaiidams/voice100/pull/40)(when it is done) to this Godot project?

**Comment by GeorgeS2019** [comment]
For users coming for Godot for Android, please check out this[ Android STT and TTS project.](https://github.com/kaiidams/Voice100AndroidApp/issues/20#issue-1099738748)

**Comment by kaiidams** [comment]
@GeorgeS2019 https://github.com/kaiidams/Voice100Sharp/pull/2
The change is still rough, but the TTS model is ready.

**Comment by GeorgeS2019** [comment]
@kaiidams 

I have followed that you have been [busy ](https://github.com/kaiidams/voice100) , any chance you will be interested in updating this project with your latest work?


Godot is now .NET6 and Godot4 with NativeAOT

**Comment by kaiidams** [comment]
@GeorgeS2019 
I need to train one more model, then will work on ONNX/C# inference
